/*
 * status.h
 *
 *  Created on: Aug 12, 2025
 *      Author: sgrujic
 */

#ifndef INCLUDE_STATUS_H_
#define INCLUDE_STATUS_H_


typedef enum {
	STATUS_OK,
	STATUS_FILE_ERROR,
	STATUS_ACCOUNT_NOT_EXISTS,
	STATUS_MAX_ATTEMPTS_REACHED,
	STATUS_PIN_INVALID,
	STATUS_ACCOUNT_TYPE_INVALID,
	STATUS_MONEY_LIMIT_REACHED,
	STATUS_INSUFFICIENT_MONEY,
	STATUS_WRONG_VALUE,
	STATUS_LIMIT_EXCEEDING,
	STATUS_ERROR,
	STATUS_UNKNOWN,
} StatusCode;

typedef struct {
	StatusCode code;
	char message[128];
} Status;

#endif /* INCLUDE_STATUS_H_ */
